personalPortfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('resume/', views.Resume.as_view(), name='resume'),
    path('references/', views.ReferencesView.as_view(), name='references'),
    path('projects/', include('projects.urls', namespace='projects'))
]

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.ProjectsView.as_view(), name='projects'),
    path('optimizer', views.PortfolioOptimizerView.as_view(), name='optimizer'),
    path('PDFencrypter', views.PDFEncrypterView.as_view(), name='encrypter'),
    path('ebay', views.EbayView.as_view(), name='ebay'),
    path('tesla', views.TeslaView.as_view(), name='tesla'),
    path('blackstone', views.BlackStoneView.as_view(), name='blackstone'),
    path('marketwrap', views.MarketWrapView.as_view(), name='marketwrap'),
    path('holdback', views.HoldbackView.as_view(), name='holdback'),

]

projects/models.py
from django.db import models

# Create your models here.

personalPortfolio/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.


class HomePage(TemplateView):
    template_name = 'index.html'


class Resume(TemplateView):
    template_name = 'resume.html'

class ReferencesView(TemplateView):
    template_name = 'references.html'

projects/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.


class ProjectsView(TemplateView):
    template_name = 'projects.html'


class PortfolioOptimizerView(TemplateView):
    template_name = 'portfolioOptimizer.html'


class PDFEncrypterView(TemplateView):
    template_name = 'pdfEncrypter.html'


class EbayView(TemplateView):
    template_name = 'eBay.html'


class TeslaView(TemplateView):
    template_name = 'tesla.html'


class BlackStoneView(TemplateView):
    template_name = 'blackstone.html'


class MarketWrapView(TemplateView):
    template_name = 'marketwrap.html'

class HoldbackView(TemplateView):
    template_name = 'holdback.html'

templates/base.html
<!DOCTYPE html> {% load staticfiles %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>BRENNER SWENSON</title>

  <!-- Latest compiled and minified CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  <scripts src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Assistant:300|Lato:300|Merriweather:300,400|PT+Serif:700|Playfair+Display" rel="stylesheet">
  <link rel="stylesheet" href="{% static '/css/tomorrow.min.css' %}">
  <link rel="stylesheet" href="{% static '/css/master.css' %}">
  <script src="{% static '/js/highlight.pack.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.3/jquery.min.js"></script>
  <script src="{% static 'slick/slick.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'slick/slick.css' %}">
  <link rel="stylesheet" href="{% static 'slick/slick-theme.css' %}">
  <script src="{% static 'js/main.js' %}">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

  <script>
    hljs.initHighlightingOnLoad();
  </script>

</head>

<body>
  <nav class="navbar navbar-expand-sm navbar-light" role='navigation' id='navbar'>
    <div class="container">
      <a href="{% url 'home' %}" class="navbar-brand nav-link fas fa-home fa-1x" id='homeButton'><i ></i></a>
      <button class="navbar-toggler navbar-toggle" type="button" data-toggle="collapse" data-target="#collapsibleNavbar" id="hamburger"><i class="fas fa-bars hamburger"></i>
  </button>
      <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
        <ul class="navbar-nav ">
          <li class='nav-item nav-text'>
            <a href="{% url 'projects:projects' %}" class="nav-link">PROJECTS</a>
          </li>
          <li class="nav-item nav-text">
            <a href="{% url 'resume' %}" class="nav-link">RESUME</a>
          </li>
          <li class='nav-item nav-text' id=>
            <a href={% url 'references' %} class="nav-link">REFERENCES</a>
          </li>
          <li class='nav-item'> <a href="https://github.com/brennerswenson"><i id="navGithubBtn" class="nav-link fab fa-github fa-2x"></i></a>
          </li>
          <li class='nav-item'> <a href="https://www.linkedin.com/in/brenner-swenson/"><i id="navLinkedInBtn" class=" nav-link fab fa-linkedin fa-2x"></i></a>
          </li>

        </ul>
      </div>

    </div>
  </nav>
  <div class="globalContainer container-fluid">
    <section class="row myContent">
      {% block content %}
      <p></p>
      {% endblock content %}
    </section>
    <footer class="footer">
      <div class="container-fluid footerContainer">
        <div class="row">
          <div class="col-sm-12 footer text-center">
            <div class="footerContent">
              <i class="fas fa-envelope fa-1x"></i>
              <p id="footerEmail">BRENNER.SWENSON@GMAIL.COM</p>
            </div>
          </div>
    </footer>
    </div>
    </div>

</body>

</html>

templates/blackstone.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
  <div class="container-fluid blackStoneContainer">
    <div class="row">
      <div class="col-lg-12 blackStoneContainer">
        <iframe class="blackStoneVideo" src="https://www.youtube.com/embed/-p662NaCTO0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
      </div>

    </div>

  </div>

{% endblock content %}

templates/eBay.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
  <div class="container-fluid ebayContainer">
    <div class="row">
      <div class="col-lg-12 ebayContainer">
        <iframe class="ebayPresentation" src="https://docs.google.com/presentation/d/e/2PACX-1vTpWJ4GbFhVjkRjWAEiwext1ZkzaSukkJGIUOXtSeRfNCuw6r8grF8mQ12lKVf9bJr0nDKGWFvdVs_P/embed?start=true&loop=true&delayms=8000" frameborder="0" width="1440" height="839" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
      </div>

    </div>

  </div>

{% endblock content %}

templates/holdback.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="container-fluid holdbackBigContainer">
  <div class="row">
    <div class="col-sm-12 holdbackTitleContainer">
      <h1 class="holdbackTitle">HEDGE FUND FULL-REDEMPTION HOLD BACK INTEREST CALCULATOR</h1>

    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 holdbackExcelLink">
      <a class="holdbackExcelLink"href="{% static '/excel/Holdback Interest Calculator.xlsx' %}" download>DOWNLOAD EXCEL FILE</a>

    </div>

  </div>
  <div class="row">
    <div class="col-sm-12 holdbackTextContainer">
      <p class="holdbackText">
        <div class="holdbackBriefExplanation">

          The spreadsheet above is something that I built while working for Strata Fund Solutions, it calculates interest for hedge fund redemption hold back balances. For confidentiality reasons I've omitted/deleted any client-specific information in this spreadsheet, including the Excel file's metadata. Here is an explanation of what the file is, and how it works:
          <br>
          <br>
          <div class="holdbackFileDisclaimer">
          (Please download the Excel file and explore while you read!)
          </div>
          <br>
        </div>
        <div class="holdbackLongExplanation">
          After my first few months at Strata Fund Solutions, we onboarded a huge client out of New York, with dozens of funds with an excess of $1bn in assets under management. Prior to hiring Strata as their administrator, they performed all of their performance
          reporting, accounting, and treasury management internally.
          <br>
          <br> The majority of this client's funds were hedge funds, which allow investors to redeem their capital with more ease compared to private equity funds, which are locked in for periods of sometimes 7 years or more.
          <br>
          <br> An investor who redeems will submit a redemption request, and then the fund has on average about a quarter or so (dependent on their limited partnership agreement) to pay out the investor's requested capital. However, as an investor's net
          asset value is constantly changing month to month, and auditors' can make income/expense adjustments, it is very common for funds to withhold, or "hold back" a small portion of an investor's capital balance (typically 5 or 10 percent) if they
          are fully redeeming--because their capital balance could change if auditors make any adjustments that affect the fund's net income.
          <br>
          <br> The hold back balance is 5% of the investor's redemption balance, so, as a provision of the Limited Partnership Agreement of our client's funds, after a quarter has passed since the redemption, they are required to pay out the amount that
          makes the investor's remaining hold back balance equal to 1% of their ending capital balance at the end of the last reporting period. This sounds very confusing, but can be seen in row I of my workbook provided.

          <br>
          <br> As a result of the fund holding this 5 or 10 percent balance, for the reason that the fund is not actively trying to produce alpha with this capital, the fund accrues a small amount of interest on these balances. The amount of interest
          is then added to the held back amount (the 1% balance that remains), and paid to the investor once the audit is completed.

          <br>
          <br> Our client used to calculate the interest amounts with an Excel tab for every limited partner (there can be hundreds of them), and with 100 - 200 rows for each day's balance, which compounds monthly. As this was not efficient, and had a
          high potential for error, my team tasked me with creating a sheet that does all of this calculation on one page, no matter how many limited partners there are. The ending result is one spreadsheet that compounds an investor's hold back interest
          amount, and uses if/else logic to determine which balance to calculate/compound the interest on, and for how many days.

          <br>
          <br> For example, if a limited partner had a hold back balance, but then the fund made a payment of the 4% in the middle of the month, then the fund would need to accrue interest on two different balances for that month: the larger balance before
          the payment was made, and the balance after the payment was made. You can see this being calculated in column AI for the month of May 2017.

          <br>
          <br> Ideally, the user of this spreadsheet would unhide the appropriate columns as the year goes on, so you can obtain the ending hold back interest payable number, which would be found in cell BO29 of the workbook. This figure would end up in
          the fund's financial statements on the balance sheet. Although immaterial, it was a very important item for our client--this workbook was sent along side monthly financial statements for our client's dozens of hedge funds.
          <br>
          <div class="holdbackLongExplanationEnd">
          <br>
          Thank you for reading, and please download the file and have a look for yourself!
          </div>
          <br>
          <br>
        </div>
      </p>

    </div>

  </div>

</div>

{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

  <div class="contentContainer container-fluid">
    <div class="row aboutMeTitleContainer">
      <p class='aboutMeTitle col-sm-12'>BRENNER SWENSON</p>
    </div>

    <div class="pageContent row">

      <div class='col-sm-6 headshotContainer'>

        <div class="headshotsGallery slider">
          <div class="headshot">
            <img class="headshot" src="{% static 'photos/brenner-headshot-3.jpg' %}" alt="">
          </div>
          <div class="headshot">
            <img class='headshot' src="{% static 'photos/brenner-wedding-1.jpg' %}" alt="">
          </div>
          <div class="headshot">
            <img class='headshot' src="{% static 'photos/brenner-headshot-2.jpg' %}" alt="">
          </div>
          <div class="headshot">
            <img class='headshot' src="{% static 'photos/brenner-france-1.jpg' %}" alt="">
          </div>

          <div class="headshot">
            <img class='headshot' src="{% static 'photos/brenner-choir-2.jpg' %}" alt="">
          </div>


          <div class="headshot">
            <img class='headshot' src="{% static 'photos/brenner-headshot-1.jpg' %}" alt="">
          </div>

          <div class="headshot">
            <img class='headshot' src="{% static 'photos/brenner-france-2.jpg' %}" alt="">
          </div>
          <div class="headshot">
            <img class='headshot' src="{% static 'photos/brenner-headshot-4.jpg' %}" alt="">
          </div>
          <div class="headshot">
            <img class='headshot' src="{% static 'photos/brenner-wedding-2.jpg' %}" alt="">
          </div>
          <div class="headshot">
            <img class='headshot' src="{% static 'photos/brenner-choir-1.jpg' %}" alt="">
          </div>
          <div class="headshot">
            <img class='headshot' src="{% static 'photos/brenner-france-3.jpg' %}" alt="">
          </div>
          <div class="headshot">
            <img class='headshot' src="{% static 'photos/brenner-headshot-5.jpg' %}" alt="">
          </div>
          <div class="headshot">
            <img class='headshot' src="{% static 'photos/brenner-choir-3.jpg' %}" alt="">
          </div>

        </div>
      </div>

      <div class="aboutMeTextContainer col-sm-6">
        <div class="fadedScrollerAboutMe">
          <p class='aboutMeText'>
            <br> My name is Brenner Swenson. I’m a young financial/data analyst recently relocated from Utah to London, with experience in finance, accounting, computer science, and music. I love applying and implementing my love for computer science concepts
          with finance, and I would love to carry out this passion of mine with a firm here in London.
          <br>
          <br> I’ve spent my last two or so years working for Strata Fund Solutions, an alternative investment fund administrator based in Salt Lake City, Utah. Here is a <a href="http://www.stratafs.com/">link</a> to their website if you are curious
          about what they do. While working as a Strata analyst, I learned an incredible amount regarding the public and private investment industries. After my first few months at Strata, one of the main senior analysts on my primary client left for
          another firm, and the client was left on my shoulders alone. I tackled this challenge and soon became the expert on this client--a private fund manager with over $215M in AUM.
          <br>
          <br> One of my main interests is computer science and its applications in finance. I am self-taught in this regard; I started to teach myself the Python programming language a few years ago, and haven’t been able to stop.
          <br>
          <br> I built this website from scratch using the Django web framework, which was written with and for Python. I built this website to primarily illustrate my projects, and I plan to keep adding to it. You can find the source code for this
          site <a href="https://github.com/brennerswenson/personalPortfolio">here</a> or on the Projects page of this website.
          <br>
          <br> I grew up in Utah, where I studied finance at the University of Utah David Eccles School of Business and graduated with a 3.86 out of 4.0. While in school, I was a member of the university’s Chamber Choir for three years. In Chamber Choir,
          I traveled through Europe, winning several international competitions, making lifelong friends and drinking great wine the whole time. I also minored in music at my university, specializing in vocal performance. Music is something that is very,
          very important to me.
          <br>
          <br> I met my dear wife Alysa at the University of Utah in a microeconomics class in 2014, and I’ve loved every minute of the four years since then. We recently got married in April of 2018; her job is what brings us out to London, and we couldn’t
          be more excited to be here.

          <br>
<br> I am always open to new opportunities, so please feel free to email me at the address below if you would like to get in touch with me. Please have a look around the site!


          </p>
        </div>
        <div class="fadedScrollerAboutMe_fade"></div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/marketwrap.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
  <div class="container-fluid blackStoneContainer">
    <div class="row">
      <div class="col-lg-12 blackStoneContainer">
        <iframe class="marketWrapVideo" src="https://www.youtube.com/embed/JtBvO3hlWQU" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
      </div>

    </div>

  </div>

{% endblock content %}

templates/pdfEncrypter.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

  <div class="portfolioEncrypterContainer container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <h1 class="encrypterTitle">PDF ENCRYPTER</h1>
        <div class="row">
          <div class="encrypterCodeColumn col-sm-5 ">
            <div class="fadedScrollerEncrypter">
              <pre><code class="encryptercodetext">
  import os
  from pypdf2 import pdffilereader, pdffilewriter
  import math
  import time
  import random
  import subprocess
  from textwrap import textwrapper
  import sys

  # terminal colors

  class bcolors:
      header = '\033[95m'
      okblue = '\033[94m'
      okgreen = '\033[92m'
      yellow = '\033[93m'
      red = '\033[91m'
      endc = '\033[0m'
      bold = '\033[1m'
      underline = '\033[4m'

  # only will protect pdfs


  def ispdffile(fname):
      if not os.path.isfile(fname):
          return false
      (name, ext) = os.path.splitext(fname)
      return ext.lower() == '.pdf'

  # create function to encrypt pdf


  def encrypt(file):
      temp = open(file, 'rb')
      temp_reader = pdffilereader(file)
      temp_writer = pdffilewriter()
      for num in range(temp_reader.numpages):
          temp_writer.addpage(temp_reader.getpage(num))
      temp_writer.encrypt(password)
      temp_result = open(file, 'wb')
      temp_writer.write(temp_result)
      temp_result.close()

  # make progress bar


  def progress(count, total, suffix=''):
      bar_len = 50
      filled_len = int(round(bar_len * count / float(total)))
      percents = round(100.0 * count / float(total), 1)
      bar = '=' * filled_len + '-' * (bar_len - filled_len)
      sys.stdout.write(bcolors.yellow + '[%s] %s%s %s\r' %
                       (bar, percents, '%', suffix) + bcolors.endc)

      sys.stdout.flush()
      if count == total:
          print(bcolors.bold + '\n' + '\ndone!\n' + bcolors.endc)


  time.sleep(.5)

  # text wrapper instance


  wrapper = textwrapper()

  wrapper.width = 80

  # make list of files to protect

  all_files = os.listdir('.')

  # empty list for pdfs

  files_to_encrypt = []

  # fill list with only pdfs

  for file in all_files:
      if ispdffile(file):
          files_to_encrypt.append(file)
      else:
          continue

  # no. of files to protect

  total = len(files_to_encrypt)

  # get directory from user

  print("\n")
  directory = input(wrapper.fill(
      'hi! welcome to strata pdf encrypter, created by brenner swenson. \nplease paste in the directory of where your pdf files are located: '))

  # checks if input is a valid directory

  if not os.path.exists(directory):

      directory = input(wrapper.fill(
          bcolors.red + "invalid directory, please enter a valid directory: " + bcolors.endc))

  # second check if input is incorrect

  if not os.path.exists(directory):

      directory = input(wrapper.fill(
          bcolors.red + "invalid directory, please enter a valid directory: " + bcolors.endc))


  if not os.path.exists(directory):

      directory = input(wrapper.fill(
          bcolors.red + "invalid directory, please enter a valid directory. last try: " + bcolors.endc))


  if not os.path.exists(directory):

      print(bcolors.red + "invalid directory, press any key to close encrypter and try again." + bcolors.endc)

      input('')

      quit()


  os.chdir(directory)

  # get password from user

  password = str(input(wrapper.fill(
      'enter password you want to encrypt all .pdf files in this directory with :  ')))

  # phrases for fun, after encryption finishes

  print('\n')

  phrases = ['now go take a long lunch. you deserve it.', 'now go thank brenner for making this, because of how much free time you have now.', 'now go take a nap with all of the time you just saved.', 'now go home at a decent time today, you just saved a bunch of time.', "go test out the files and make sure brenner didn't screw up. he probably made some mistake somewhere.",
             'now go watch a youtube video or something, you have some free time now. watching cat videos is beneficial to your mental health.', 'go test out your files! make sure the password actually works.',  'have an idea for a script that brenner could make? let him know!']

  # enables terminal coloring

  subprocess.call('', shell=true)

  start_time = time.time()

  count = 0

  print('here we go...')
  print('')

  import concurrent.futures

  # create 4 python instances for fast execution

  with concurrent.futures.threadpoolexecutor() as executor:
      futures = {executor.submit(encrypt, file)               : file for file in files_to_encrypt}

      for future in concurrent.futures.as_completed(futures):
          count += 1
          # progress bar
          progress(count, total, suffix='encrypting pdf {z} of {y}...'.format(
              z=count, y=len(files_to_encrypt)))

  # calculating performance time
  end_time = time.time()
  execution_time_secs = math.ceil(end_time - start_time)
  execution_time_mins = ((end_time - start_time) / 60)
  files_per_second = (count / execution_time_secs)

  # message to display performance, formatting

  msg = "{d} seconds, or {e:.{digits}f} minutes. that's about {g:.{digits}f} files per second." .format(
      d=execution_time_secs, e=execution_time_mins, digits=2, g=files_per_second)

  # finishing text

  print(bcolors.okgreen + '{a} files encrypted in {c} {b}'.format(a=count,
                                                                  b=wrapper.fill(random.choice(phrases)), c=wrapper.fill(msg)) + bcolors.endc)

  print('')
  time.sleep(1)

  print('')

  input(bcolors.bold + "press any key to exit." + bcolors.endc)


          </code></pre>
            </div>

            <div class="fadedScrollerEncrypter_fade"></div>
          </div>
          <div class="encrypterExplanationColumn col-sm-7">
            <div class="fadedScrollerEncrypter">

              <div class="row">

                <div class="encrypterContentWrapper col-sm-12">
                  <iframe class="encrypterContent" src="https://www.youtube.com/embed/GqpJLdl2Vq8" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen="allowfullscreen"></iframe>
                </div>

              </div>
              <div class="encrypterExplanationText row">
                <p>
                At my last job, one of our main responsibilities was preparing investor statements for our clients’ hedge/private equity funds. These statements contain very sensitive information, such as the net asset value of their investments, their addresses, etc.. We would then distribute these documents directly to investors via email, or via a portal depending on the client.</p>
<p>
In addition to investor statements, Strata, the company I worked for, prepared a lot of tax documents for our clients. Schedule K-1s are very similar to a form 1099, which shows investment income, except K-1s are for the alternative investment industry. These documents are very sensitive and contain annual investment income figures as well as Social Security numbers. Not only does Strata prepare some tax documents, but if our clients had other tax-preparers, those tax preparers would send to us the K-1s they prepared for distribution to investors.
More often than not, we needed to distribute these documents via email, directly to the investor as it is the most direct way to ensure that they have in fact received their K-1/investor statement. However, the documents needed to be password protected, which takes a lot of time. To do it manually, you have to open the pdf, go through the settings, get to the settings window, select security, and paste in the predetermined password. Some of our clients’ funds have in excess of 300 investors, when compiled with other clients, this is a lot of mundane work just in order to protect files. With investor statements, this would happen monthly for some clients.
</p>
<p>
In my spare time, I developed this script which can password protect any amount of pdfs in a small fraction of the time it previously took. The video above shows how quickly it can protect 500 pdfs.
I won’t go into the detail of how it works, as you can see it on the left. Essentially, it gathers a list of all files in the current directory that are pdfs, then iterates through the list, opening the pdf, calling encrypt() on said file, and closing the file before moving on to the next one.
</p>
<p>
I created this several months prior to leaving my last job and it saved my team hours of work, as I showed them how to use it on their own machines! My managers and supervisors were thrilled at this, and so was I, because I love ad hoc projects like this one.
</p>
</div>
            </div>
            <div class="fadedScrollerEncrypter_fade"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/projects.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<div class="projectsContainer container-fluid">
  <div class="row">
    <p class='col-lg-12 projectsTitle'>PROJECTS</p>
  </div>
  <div class="row projectList">
    <div class="projectsButtonContainer">


      <ul class='col-lg-12'>
        <li class="project">
          <a class="btn btn-primary btn-lg btn-block projectButton" href="http://www.github.com/brennerswenson/personalPortfolio" role='button'>THIS WEBSITE</a>
        </li>
        <li class="project">
          <a class="btn btn-primary btn-lg btn-block projectButton" href="{% url 'projects:optimizer'%}" role='button'>PORTFOLIO WEIGHTS AND SHARPE RATIO OPTIMIZER</a>
        </li>
        <li class="project">
          <a class="btn btn-primary btn-lg btn-block projectButton" href=" {% url 'projects:encrypter'%} " role='button'>PDF ENCRYPTER</a>
        </li>
        {% comment %}
        <li class="project">
          <a href="http://www.quantopian.com">
            Trading algorithms</a>
        </li> {% endcomment %}
        <li class="project">
          <a class="btn btn-primary btn-lg btn-block projectButton" href=" {% url 'projects:holdback' %}" role='button'>HEDGE FUND FULL-REDEMPTION HOLD BACK INTEREST CALCULATOR</a>
        </li>
        <li class="project">
          <a class="btn btn-primary btn-lg btn-block projectButton" href="{% url 'projects:tesla' %}" role='button'>
            TESLA BUSINESS MODEL EVALUATION</a>
        </li>
        <li class="project">
          <a class="btn btn-primary btn-lg btn-block projectButton" href="{% url 'projects:ebay' %}" role='button'>
            EBAY OUTSOURCING CASE STUDY</a>
        </li>
        <li class="project">
          <a class="btn btn-primary btn-lg btn-block projectButton" href="{% url 'projects:blackstone' %}" role='button'>
            HILTON BLACKSTONE HOTELS LEVERAGED BUYOUT ANALYSIS</a>
        </li>
        <li class="project">
          <a class="btn btn-primary btn-lg btn-block projectButton" href="{% url 'projects:marketwrap' %}" role='button'>
            WEEKLY MARKET DEVELOPMENTS 22/3/2017
          </a>
        </li>
        <li class='desktopDisclaimer'> <p>Projects are best viewed on a desktop</p> </li>
      </ul>
    </div>
  </div>

</div>

{% endblock content %}

templates/resume.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
  <div class="container-fluid resumeContainer">
    <div class="resumeTitleRow row">
      <h1 class="resumeTitle col-sm-12 center-block text-center" >RESUME</h1>
    </div>
    <div class="resumeBorderRow row">

    </div>
    <div class="resumeRow row">
      <div id="resume" class='col-sm-6'>
        <script src="{% static 'js/pdfobject.js' %}"></script>
        <script>
          PDFObject.embed("{% static 'pdfs/BRENNER SWENSON RESUME.pdf' %}", "#resume");
        </script>

      </div>
    </div>

  </div>

{% endblock content %}

templates/tesla.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
  <div class="container-fluid teslaContainer">
    <div class="row">
      <div class="col-lg-12 teslaContainer">
        <iframe class="teslaPresentation"
          src="https://docs.google.com/presentation/d/e/2PACX-1vTnN4-54_ztiamfS7wGSWmYpAg6JzeUvrvHo9Atyb83tpaeFH1nCTIPxZsmxaGrPqXYRIKq-xDu3Jo0/embed?start=false&loop=false&delayms=8000"
          frameborder="0"
          width="1440"
          height="839"
          allowfullscreen="true"
          mozallowfullscreen="true"
          webkitallowfullscreen="true"></iframe>
      </div>

    </div>

  </div>

{% endblock content %}